#!/bin/sh

set -eu

test -x /usr/bin/bootctl || exit 0

bootctl is-installed >/dev/null || exit 0

echo "Updating kernel version $1 in systemd-boot..."

kernel-install add "$1" "/boot/vmlinuz-$1" "$2"
